anchor_version = "0.24.2"
solana_version = "1.9.12"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[scripts]
test = "yarn mocha"

# StableSwap
[[test.genesis]]
address = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
program = "./artifacts/deploy/stable_swap.so"

[programs.mainnet]
pools = "SMANK4F5osjfVpKFH5LPzE6HPpbzSPu5iHPBhuor5xU"

[programs.devnet]
pools = "SMANK4F5osjfVpKFH5LPzE6HPpbzSPu5iHPBhuor5xU"

[programs.testnet]
pools = "SMANK4F5osjfVpKFH5LPzE6HPpbzSPu5iHPBhuor5xU"

[programs.localnet]
pools = "SMANK4F5osjfVpKFH5LPzE6HPpbzSPu5iHPBhuor5xU"
